En 10585 implement smart contract result processor
ElrondNetwork/covalent-indexer-go pull request #5
Opened 2021-08-19 12:55 UTC by mariusmihaic

DUMMY PR

2021-08-25 13:18 UTC, AdoAdoAdo reviewed
Todo: check for tests requires the parameters order.

2021-08-25 13:28 UTC, AdoAdoAdo approved these changes

2021-08-25 15:44 UTC, miiu96 requested changes

2021-08-25 15:44 UTC, miiu96 commented on process/data_processor.go
> +	smartContracts := dp.scHandler.ProcessSCs(args.TransactionsPool.Scrs, args.Header.GetTimeStamp())
these aren't smart contracts ---> are smart contract results

2021-08-25 15:44 UTC, miiu96 commented on process/factory/data_processor_factory.go
> +	scHandler, err := transactions.NewSCProcessor(args.PubKeyConvertor)
scResultsHandler
`sc` -- makes me think at a smart contract not to smart contract results

2021-08-25 15:44 UTC, miiu96 commented on process/interface.go
>  type SCHandler interface {
This should be renamed in `SCResultsHandler` or something similar

2021-08-25 15:44 UTC, miiu96 commented on process/transactions/sc_processor.go
> +func NewSCProcessor(pubKeyConverter core.PubkeyConverter) (*scProcessor, error) {
`NewSCResultsProcessor`

2021-08-25 15:44 UTC, miiu96 commented on process/transactions/sc_processor_test.go
> +	"testing"
sort imports

2021-08-25 15:44 UTC, miiu96 commented on process/transactions/sc_processor_test.go
> +	require.Equal(t, ret[0].Hash, []byte("hash1"))
instead of checking every field from resulted SCR you can create an expectedSmartContractResult with all the fields that are expected

2021-08-25 15:44 UTC, miiu96 commented on process/transactions/sc_processor.go
> +	allSCRs := make([]*schema.SCResult, 0)
`allSCRs := make([]*schema.SCResult, 0, len(transactions))`

2021-08-25 15:44 UTC, miiu96 commented on process/transactions/sc_processor.go
> +func NewSCProcessor(pubKeyConverter core.PubkeyConverter) (*scProcessor, error) {
also rename the file name

2021-08-26 08:05 UTC, mariusmihaic commented on process/data_processor.go
> +	smartContracts := dp.scHandler.ProcessSCs(args.TransactionsPool.Scrs, args.Header.GetTimeStamp())
Renamed it

2021-08-26 08:06 UTC, mariusmihaic commented on process/factory/data_processor_factory.go
> +	scHandler, err := transactions.NewSCProcessor(args.PubKeyConvertor)
Renamed it

2021-08-26 08:06 UTC, mariusmihaic commented on process/interface.go
>  type SCHandler interface {
Renamed it

2021-08-26 08:07 UTC, mariusmihaic commented on process/transactions/sc_processor.go
> +func NewSCProcessor(pubKeyConverter core.PubkeyConverter) (*scProcessor, error) {
Done

2021-08-26 08:08 UTC, mariusmihaic commented on process/transactions/sc_processor_test.go
> +	"testing"
Done

2021-08-26 08:14 UTC, mariusmihaic commented on process/transactions/sc_processor_test.go
> +	require.Equal(t, ret[0].Hash, []byte("hash1"))
These tests are refactored in a future PR.

> you can create an expectedSmartContractResult with all the fields that are expected

However, they do not follow this approach, as this is what I tried to avoid. Imagine I create 7 txs objects => then I have to create another 7 processed txs objects. Instead I've created a function that checks each field=> way less repetitive code

2021-08-26 08:16 UTC, mariusmihaic commented on process/transactions/sc_processor.go
> +	allSCRs := make([]*schema.SCResult, 0)
Done

2021-08-26 08:25 UTC, miiu96 approved these changes

2021-08-26 08:31 UTC, merged