En 10588 implement receipts processor
ElrondNetwork/covalent-indexer-go pull request #7
Opened 2021-08-20 15:07 UTC by mariusmihaic

2021-08-25 13:27 UTC, AdoAdoAdo approved these changes
todo: 
- param order for tests require
- goimports

2021-08-25 15:47 UTC, miiu96 requested changes

2021-08-25 15:47 UTC, miiu96 commented on process/receipts/receipts_processor.go
> +	return &receiptsProcessor{pubKeyConverter: pubKeyConverter}, nil
split in multiple lines

2021-08-25 15:47 UTC, miiu96 commented on process/receipts/receipts_processor.go
> +	allReceipts := make([]*schema.Receipt, 0)
allReceipts := make([]*schema.Receipt, 0, len(receipts))

2021-08-25 15:47 UTC, miiu96 commented on process/receipts/receipts_processor.go
> +	timeStamp uint64) *schema.Receipt {
add empty line

2021-08-25 15:47 UTC, miiu96 commented on process/receipts/receipts_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/process/utility"
sort imports

2021-08-25 15:47 UTC, miiu96 commented on process/transactions/sc_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/process/utility"
sort imports

2021-08-26 08:23 UTC, mariusmihaic commented on process/receipts/receipts_processor.go
> +	return &receiptsProcessor{pubKeyConverter: pubKeyConverter}, nil
Done

2021-08-26 08:24 UTC, mariusmihaic commented on process/receipts/receipts_processor.go
> +	allReceipts := make([]*schema.Receipt, 0)
Done

2021-08-26 08:25 UTC, mariusmihaic commented on process/receipts/receipts_processor.go
> +	timeStamp uint64) *schema.Receipt {
Done

2021-08-26 08:25 UTC, mariusmihaic commented on process/receipts/receipts_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/process/utility"
Done

2021-08-26 08:25 UTC, mariusmihaic commented on process/transactions/sc_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/process/utility"
Done

2021-08-26 08:28 UTC, AdoAdoAdo reviewed
fixes to be done on EN-10606-Review_fixes

2021-08-26 08:31 UTC, merged