En 10589 implement logs and events processor
ElrondNetwork/covalent-indexer-go pull request #8
Opened 2021-08-23 09:34 UTC by mariusmihaic

2021-08-25 14:02 UTC, AdoAdoAdo approved these changes

2021-08-25 15:54 UTC, miiu96 requested changes

2021-08-25 15:54 UTC, miiu96 commented on process/logs/logs_processor.go
> +	return &logsProcessor{pubKeyConverter: pubKeyConverter}, nil
split in multiple lines

2021-08-25 15:54 UTC, miiu96 commented on process/logs/logs_processor.go
> +	allLogs := make([]*schema.Log, 0)
allLogs := make([]*schema.Log, 0, len(logs))

2021-08-25 15:54 UTC, miiu96 commented on process/logs/logs_processor.go
> +	allLogs := make([]*schema.Log, 0)
this can be renamed. don't like the current name. maybe you can rename in `dbLogs` or something that suggests that you have converted the logs.

2021-08-25 15:54 UTC, miiu96 commented on process/logs/logs_processor.go
> +	allEvents := make([]*schema.Event, 0)
allEvents := make([]*schema.Event, 0, len(events))

2021-08-25 15:54 UTC, miiu96 commented on process/logs/logs_processor.go
> +	allEvents := make([]*schema.Event, 0)
also please rename

2021-08-25 15:54 UTC, miiu96 commented on process/logs/logs_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/process/logs"
sort imports

2021-08-25 15:54 UTC, miiu96 commented on process/transactions/sc_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/testscommon"
sort imports

2021-08-25 15:54 UTC, miiu96 commented on process/transactions/transactions_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/testscommon"
sort imports

2021-08-25 15:54 UTC, miiu96 commented on testscommon/data_generator.go
> +func GenerateRandomBytes() []byte {
add comment for exported function

2021-08-25 15:54 UTC, miiu96 commented on testscommon/data_generator.go
> +func GenerateRandomBigInt() *big.Int {
add a comment for the exported function

2021-08-26 08:25 UTC, miiu96 approved these changes

2021-08-26 08:28 UTC, mariusmihaic commented on process/logs/logs_processor.go
> +	return &logsProcessor{pubKeyConverter: pubKeyConverter}, nil
Done

2021-08-26 08:29 UTC, AdoAdoAdo reviewed
fixes to be done on EN-10606-Review_fixes

2021-08-26 08:31 UTC, merged

2021-08-26 09:06 UTC, mariusmihaic commented on process/logs/logs_processor.go
> +	allLogs := make([]*schema.Log, 0)
> allLogs := make([]*schema.Log, 0, len(logs))

Done

> this can be renamed. don't like the current name. maybe you can rename in dbLogs or something that suggests that you have converted the logs.

I disagree with this, because upon initialization of `allLogs` , you can already deduce that it is of `[]*schema.Log` type

2021-08-26 09:08 UTC, mariusmihaic commented on process/logs/logs_processor.go
> +	allEvents := make([]*schema.Event, 0)
Done first part, regarding second comment, please read the comment above.

2021-08-26 09:08 UTC, mariusmihaic commented on process/logs/logs_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/process/logs"
Done

2021-08-26 09:12 UTC, mariusmihaic commented on process/transactions/sc_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/testscommon"
Done

2021-08-26 09:12 UTC, mariusmihaic commented on process/transactions/transactions_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/testscommon"
Done

2021-08-26 09:14 UTC, mariusmihaic commented on testscommon/data_generator.go
> +func GenerateRandomBytes() []byte {
Done

2021-08-26 09:14 UTC, mariusmihaic commented on testscommon/data_generator.go
> +func GenerateRandomBigInt() *big.Int {
Done