En 10591 implement accounts processor
ElrondNetwork/covalent-indexer-go pull request #9
Opened 2021-08-24 13:44 UTC by mariusmihaic

2021-08-25 16:00 UTC, miiu96 requested changes

2021-08-25 16:00 UTC, miiu96 commented on errors.go
>  var ErrBlockBodyAssertion = errors.New("error asserting BodyHandler interface of type block body")
add PR description

2021-08-25 16:00 UTC, miiu96 commented on process/accounts/accounts_processor.go
> +	pubKeyConverter core.PubkeyConverter) (*accountsProcessor, error) {
split in multiple lines

2021-08-25 16:00 UTC, miiu96 commented on process/accounts/accounts_processor.go
> +	processedReceipts []*schema.Receipt) []*schema.AccountBalanceUpdate {
split in multiple lines

2021-08-25 16:00 UTC, miiu96 commented on process/accounts/accounts_processor.go
> +			log.Warn("cannot get address account", "address", address, "error", err)
`**address** should be encoded here`

2021-08-25 16:00 UTC, miiu96 commented on process/accounts/accounts_processor.go
> +	accounts := make([]*schema.AccountBalanceUpdate, 0)
`accounts := make([]*schema.AccountBalanceUpdate, 0, len(addresses))`

2021-08-25 16:00 UTC, miiu96 commented on process/accounts/accounts_processor.go
> +	for _, tx := range processedTxs {
:+1:

2021-08-25 16:00 UTC, miiu96 commented on process/accounts/accounts_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/process/accounts"
sort imports

2021-08-25 16:00 UTC, miiu96 commented on testscommon/mock/shard_coordinator_stub.go
> +package mock
rename file name --> this a mock not a stub

2021-08-25 16:00 UTC, miiu96 commented on testscommon/mock/user_account_stub.go
> +func (uas *UserAccountStub) IncreaseNonce(_ uint64) {
this is a mock not a stub

2021-08-26 08:01 UTC, AdoAdoAdo commented on process/accounts/accounts_processor.go
> +	acc, err := ap.accounts.LoadAccount([]byte(address))
this will only work if the indexer is part of the elrond client binary, it will not work if we have two separate binaries.
Can you add a TODO on this file, that each account content should be given as well as parameter.

2021-08-26 08:25 UTC, miiu96 approved these changes

2021-08-26 08:29 UTC, AdoAdoAdo approved these changes
fixes to be done on EN-10606-Review_fixes

2021-08-26 08:31 UTC, merged

2021-08-26 09:16 UTC, mariusmihaic commented on process/accounts/accounts_processor.go
> +	pubKeyConverter core.PubkeyConverter) (*accountsProcessor, error) {
Done

2021-08-26 09:16 UTC, mariusmihaic commented on process/accounts/accounts_processor.go
> +	processedReceipts []*schema.Receipt) []*schema.AccountBalanceUpdate {
Done

2021-08-26 09:22 UTC, mariusmihaic commented on process/accounts/accounts_processor.go
> +			log.Warn("cannot get address account", "address", address, "error", err)
Good finding, yes, changed it

2021-08-26 09:23 UTC, mariusmihaic commented on process/accounts/accounts_processor.go
> +	accounts := make([]*schema.AccountBalanceUpdate, 0)
Done

2021-08-26 09:24 UTC, mariusmihaic commented on process/accounts/accounts_processor.go
> +	for _, tx := range processedTxs {
Thanks !

2021-08-26 09:24 UTC, mariusmihaic commented on process/accounts/accounts_processor_test.go
> +	"github.com/ElrondNetwork/covalent-indexer-go/process/accounts"
Done

2021-08-26 09:26 UTC, mariusmihaic commented on testscommon/mock/user_account_stub.go
> +func (uas *UserAccountStub) IncreaseNonce(_ uint64) {
Done

2021-08-26 09:31 UTC, mariusmihaic commented on process/accounts/accounts_processor.go
> +	acc, err := ap.accounts.LoadAccount([]byte(address))
Done, added a TODO here